const userData = [
  {
    firstName: "Pail",
    lastName: "Colegrove",
    email: "pail.colegrove@yolasite.com",
    username: "pail.colegrove@yolasite.com",
    password: "wvIeDLqf",
  },
  {
    firstName: "Angelica",
    lastName: "Gawkroge",
    email: "angelica.gawkroge@mtv.com",
    username: "angelica.gawkroge@mtv.com",
    password: "ZWfuqRnarS",
  },
  {
    firstName: "Jasen",
    lastName: "Franceschino",
    email: "jasen.franceschino@mapy.cz",
    username: "jasen.franceschino@mapy.cz",
    password: "Y9tu4gGMJj",
  },
  {
    firstName: "Lewes",
    lastName: "Balazot",
    email: "lewes.balazot@un.org",
    username: "lewes.balazot@un.org",
    password: "nK6NKhzCUp",
  },
  {
    firstName: "Claudianus",
    lastName: "Spalls",
    email: "claudianus.spalls@baidu.com",
    username: "claudianus.spalls@baidu.com",
    password: "NWQMvf3",
  },
  {
    firstName: "Yoko",
    lastName: "Ferne",
    email: "yoko.ferne@techcrunch.com",
    username: "yoko.ferne@techcrunch.com",
    password: "dYhzi28TMM",
  },
  {
    firstName: "Christoph",
    lastName: "Cargen",
    email: "christoph.cargen@noaa.gov",
    username: "christoph.cargen@noaa.gov",
    password: "oHhi2zGSr",
  },
  {
    firstName: "Temple",
    lastName: "Le Page",
    email: "temple.le page@barnesandnoble.com",
    username: "temple.le page@barnesandnoble.com",
    password: "aPfTGzli6",
  },
  {
    firstName: "Timofei",
    lastName: "Surcombe",
    email: "timofei.surcombe@360.cn",
    username: "timofei.surcombe@360.cn",
    password: "OkdtKCJL",
  },
  {
    firstName: "Jami",
    lastName: "Coulthard",
    email: "jami.coulthard@ucoz.com",
    username: "jami.coulthard@ucoz.com",
    password: "PcIQA0X",
  },
  {
    firstName: "Kort",
    lastName: "Curnok",
    email: "kort.curnok@cam.ac.uk",
    username: "kort.curnok@cam.ac.uk",
    password: "V19itX",
  },
  {
    firstName: "Allister",
    lastName: "Dundredge",
    email: "allister.dundredge@clickbank.net",
    username: "allister.dundredge@clickbank.net",
    password: "2UyngGS",
  },
  {
    firstName: "Estelle",
    lastName: "Leipelt",
    email: "estelle.leipelt@skyrock.com",
    username: "estelle.leipelt@skyrock.com",
    password: "qwvBN40ZAosG",
  },
  {
    firstName: "Clea",
    lastName: "Lynes",
    email: "clea.lynes@wiley.com",
    username: "clea.lynes@wiley.com",
    password: "9BSdtDl",
  },
  {
    firstName: "Nealy",
    lastName: "Pikett",
    email: "nealy.pikett@taobao.com",
    username: "nealy.pikett@taobao.com",
    password: "vppNNTlj",
  },
  {
    firstName: "Martin",
    lastName: "Scargle",
    email: "martin.scargle@ifeng.com",
    username: "martin.scargle@ifeng.com",
    password: "n3ZsC0thf",
  },
  {
    firstName: "Persis",
    lastName: "Withrington",
    email: "persis.withrington@patch.com",
    username: "persis.withrington@patch.com",
    password: "hmI9O54O",
  },
  {
    firstName: "Jordan",
    lastName: "Dmytryk",

    email: "jordan.dmytryk@nymag.com",
    username: "jordan.dmytryk@nymag.com",
    password: "nVmugw37cBK4",
  },
  {
    firstName: "Winfield",
    lastName: "Cholton",
    email: "winfield.cholton@nbcnews.com",
    username: "winfield.cholton@nbcnews.com",
    password: "3hgYpxvFshc",
  },
  {
    firstName: "Nikolia",
    lastName: "Koche",
    email: "nikolia.koche@pen.io",
    username: "nikolia.koche@pen.io",
    password: "SZR9xU",
  },
  {
    firstName: "Florance",
    lastName: "MacAlinden",
    email: "florance.macalinden@desdev.cn",
    username: "florance.macalinden@desdev.cn",
    password: "yZqI44Oz53zl",
  },
  {
    firstName: "Norma",
    lastName: "Hanse",
    email: "norma.hanse@deliciousdays.com",
    username: "norma.hanse@deliciousdays.com",
    password: "8qhljRj",
  },
  {
    firstName: "Zeke",
    lastName: "Coller",
    email: "zeke.coller@flickr.com",
    username: "zeke.coller@flickr.com",
    password: "g8nBqtIOZ7g",
  },
  {
    firstName: "Judah",
    lastName: "Girardeau",
    email: "judah.girardeau@go.com",
    username: "judah.girardeau@go.com",
    password: "IjwfsqmM9Q2a",
  },
  {
    firstName: "Chet",
    lastName: "Briddle",
    email: "chet.briddle@archive.org",
    username: "chet.briddle@archive.org",
    password: "ZgKhYKSprtX",
  },
];

module.exports = userData